# Generated by Django 4.2.30 on 2026-07-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_membershipplan_options_and_more'),
        ('accounts', '0002_remove_profile_fitness_goal_remove_profile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='membership_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='current_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='catalog.membershipplan'),
        ),
    ]
