# Generated by Django 4.2.30 on 2026-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('target', models.CharField(blank=True, max_length=100)),
                ('equipment', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('mechanic', models.CharField(blank=True, max_length=50)),
                ('force', models.CharField(blank=True, max_length=50)),
                ('instructions', models.JSONField(blank=True, default=list)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('gif_url', models.URLField(blank=True, max_length=500)),
                ('recommended_sets', models.CharField(blank=True, max_length=30)),
                ('recommended_reps', models.CharField(blank=True, max_length=30)),
                ('calories_per_minute', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
