# Generated by Django 4.2.30 on 2026-07-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
