# Generated by Django 4.2.30 on 2026-07-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'ordering': ['tier_order']},
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='tier_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Basic = 1, Premium = 2, Elite = 3', null=True, unique=True),
        ),
    ]
