# Generated by Django 4.2.30 on 2026-07-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_membershipplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='tier_order',
            field=models.PositiveSmallIntegerField(help_text='Basic = 1, Premium = 2, Elite = 3', unique=True),
        ),
    ]
