# Generated by Django 4.2.30 on 2026-07-19 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='membership_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_product', to='catalog.membershipplan'),
        ),
    ]
