# Generated by Django 4.2.30 on 2026-07-19 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_membership_plan'),
        ('cart', '0002_order_paid_at_order_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_order_items', to='catalog.membershipplan'),
        ),
    ]
